version: '3.8'

services:
  gpu-text-service:
    build: .
    ports:
      - "8080:8080"
      - "11434:11434"
    volumes:
      - ./app:/app/app
      - ollama-models:/root/.ollama
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - OLLAMA_HOST=http://localhost:11434
      - OLLAMA_MODEL=llama3.1:70b
      - MAX_TOKENS=131072
      - MAX_CONTEXT_LENGTH=131072
      # Phase 2 - Redis Configuration (commented out)
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 80G
    shm_size: '16gb'
    ulimits:
      memlock: -1
      stack: 67108864

  # Phase 2 - Redis Service (commented out)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

volumes:
  ollama-models:
  # Phase 2 - Redis Volume (commented out)
  # redis-data:
