version: '3.8'

services:
  gpu-text-service:
    build: .
    ports:
      - "8080:8080"
      - "11434:11434"
    volumes:
      - ./app:/app/app
      - ollama-models:/root/.ollama
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - OLLAMA_HOST=http://localhost:11434
      - OLLAMA_MODEL=llama3.1:70b
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 80G  # Ensure enough memory for the 70B parameter model
    shm_size: '16gb'  # Increase shared memory size

volumes:
  ollama-models:
