# .github/workflows/dev.yml
name: Development CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest tests/

  trigger-dockerhub:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Trigger DockerHub Build
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"source_type": "Branch", "source_name": "dev"}' \
          https://hub.docker.com/api/build/v1/source/${{ secrets.DOCKERHUB_USERNAME }}/gpu-text/trigger/${{ secrets.DOCKERHUB_TRIGGER_TOKEN }}/
